from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
import gzip
import json
from pathlib import Path
import re
import time
from typing import Any, Iterable

from packages.cgsr.cgsr.ingestion.source_reader import clean_source_text, detect_language
from packages.cgsr.cgsr.ingestion.verification_gate import has_mock_signal

from .verified_payload_feeder import stable_hash


PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "data" / "cloud_brain" / "approved_payloads" / "public_corpus"
DEFAULT_AUDIT_DIR = PROJECT_ROOT / "data" / "audits" / "public_corpus_builder"
COLLECTOR_VERSION = "public_corpus_shard_builder_v1"

MOJIBAKE_RE = re.compile(r"\ufffd|Ã|Â|ì|í|ê|횄|횂|챙|筌|�")
HTML_RE = re.compile(r"<[A-Za-z/][^>]*>|&(?:nbsp|amp|lt|gt|quot);")
LIST_TABLE_RE = re.compile(r"^\s*(?:\||!|\*{2,}|[#;:]{2,}|\{\||\|})")
PRIVATE_RE = re.compile(r"\b(private|personal|secret|password|api[_-]?key|payload vault)\b", re.IGNORECASE)
GENERATED_RE = re.compile(r"\b(generated by|assistant answer|chatgpt|model output|llm response)\b", re.IGNORECASE)
EVAL_RE = re.compile(r"\b(eval row|evaluation set|seed 33033|held[- ]out|benchmark answer)\b", re.IGNORECASE)

ALLOWED_LICENSE_MARKERS = (
    "cc by-sa",
    "cc-by-sa",
    "cc by ",
    "cc-by ",
    "cc0",
    "public domain",
    "public-domain",
    "open government licence",
    "공공누리",
)


def utc_now() -> str:
    """Return a compact UTC timestamp."""

    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


@dataclass(frozen=True)
class PublicCorpusBuilderConfig:
    """Configuration for converting local public corpus files into approved rows."""

    input_file: str
    source_name: str
    license_hint: str
    language: str = "ko"
    source_url: str = ""
    output_dir: str = str(DEFAULT_OUTPUT_DIR)
    audit_dir: str = str(DEFAULT_AUDIT_DIR)
    max_rows: int | None = None
    max_seconds: float | None = None
    min_chars: int = 24
    max_chars: int = 1200
    dry_run: bool = True
    execute: bool = False
    dedupe_against_dir: str | None = None
    sample_report: int = 10


@dataclass(frozen=True)
class PublicCorpusShardBuildResult:
    """Summary of one public corpus shard builder run."""

    state: str
    mode: str
    rows_read: int
    rows_accepted: int
    rows_rejected: int
    duplicate_rows: int
    rejection_reasons: dict[str, int]
    output_path: str | None = None
    audit_path: str | None = None
    source_mode: str = "local_dump_shard"
    source_type: str = "local_public_corpus_shard"
    production_store_mutated: bool = False
    local_brain_write: bool = False
    external_llm_used: bool = False
    mock_growth: bool = False
    pair_edges_sent: int = 0
    samples: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serializable result."""

        return asdict(self)


def _license_allowed(value: str) -> bool:
    lowered = str(value or "").casefold()
    return any(marker in lowered for marker in ALLOWED_LICENSE_MARKERS)


def _open_text_lines(path: Path) -> Iterable[str]:
    if path.suffix.lower() == ".gz":
        with gzip.open(path, "rt", encoding="utf-8", errors="strict") as handle:
            yield from handle
        return
    with path.open("r", encoding="utf-8", errors="strict") as handle:
        yield from handle


def _iter_source_records(path: Path, fallback_license: str) -> Iterable[dict[str, Any]]:
    """Yield line-scoped records from JSONL, text, or gzipped variants."""

    suffixes = [suffix.lower() for suffix in path.suffixes]
    is_jsonl = ".jsonl" in suffixes
    for index, line in enumerate(_open_text_lines(path), start=1):
        raw = line.strip()
        if not raw:
            continue
        if is_jsonl:
            try:
                parsed = json.loads(raw)
            except json.JSONDecodeError:
                yield {"text": "", "line_number": index, "record_index": index, "parse_error": "invalid_json"}
                continue
            if not isinstance(parsed, dict):
                yield {"text": "", "line_number": index, "record_index": index, "parse_error": "non_object_json"}
                continue
            text = str(parsed.get("text") or parsed.get("sentence") or parsed.get("extract") or parsed.get("body") or "").strip()
            yield {
                "text": text,
                "title": parsed.get("title"),
                "source_url": parsed.get("source_url") or parsed.get("url"),
                "license": parsed.get("license_hint") or parsed.get("license") or fallback_license,
                "language": parsed.get("language"),
                "source_id": parsed.get("source_id"),
                "line_number": index,
                "record_index": index,
            }
        else:
            yield {
                "text": raw,
                "title": None,
                "source_url": None,
                "license": fallback_license,
                "language": None,
                "source_id": None,
                "line_number": index,
                "record_index": index,
            }


def _quality_reasons(text: str, *, license_hint: str, min_chars: int, max_chars: int) -> list[str]:
    normalized = clean_source_text(text)
    reasons: list[str] = []
    if not _license_allowed(license_hint):
        reasons.append("unknown_license")
    if len(normalized) < min_chars:
        reasons.append("too_short")
    if len(normalized) > max_chars:
        reasons.append("too_long")
    if MOJIBAKE_RE.search(normalized):
        reasons.append("mojibake")
    if HTML_RE.search(text):
        reasons.append("html_residue")
    if LIST_TABLE_RE.search(text):
        reasons.append("table_or_list_residue")
    if PRIVATE_RE.search(normalized):
        reasons.append("private_marker")
    if re.search(r"[A-Za-z]:\\|/Users/|/home/|\\\\", normalized):
        reasons.append("local_path_leakage")
    if GENERATED_RE.search(normalized):
        reasons.append("generated_marker")
    if EVAL_RE.search(normalized):
        reasons.append("eval_marker")
    if has_mock_signal(normalized, text):
        reasons.append("mock_marker")
    alpha_count = sum(1 for char in normalized if char.isalpha())
    if normalized and alpha_count / max(1, len(normalized)) < 0.35:
        reasons.append("low_alpha_ratio")
    return reasons


def _load_dedupe_hashes(path: str | None) -> set[str]:
    root = Path(path) if path else None
    if not root or not root.exists():
        return set()
    hashes: set[str] = set()
    for item in root.rglob("*.jsonl"):
        try:
            lines = item.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            continue
        for line in lines:
            if not line.strip():
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            value = row.get("normalized_text_hash")
            if value:
                hashes.add(str(value))
    return hashes


def _approved_row(
    *,
    config: PublicCorpusBuilderConfig,
    record: dict[str, Any],
    normalized: str,
    normalized_hash: str,
    shard_id: str,
    index: int,
    collected_at: str,
) -> dict[str, Any]:
    source_id = str(record.get("source_id") or f"{config.source_name}:{record.get('line_number') or index}")
    source_path = str(record.get("source_url") or config.source_url or Path(config.input_file).resolve())
    provenance_hash = stable_hash(f"local_public_corpus_shard:{source_id}:{source_path}:{normalized_hash}")
    raw_text = str(record.get("text") or "")
    return {
        "payload_id": f"public_corpus_{provenance_hash[:24]}",
        "source_type": "local_public_corpus_shard",
        "source_mode": "local_dump_shard",
        "source_id": source_id,
        "source_url_or_path": source_path,
        "source_title": str(record.get("title") or config.source_name),
        "license_hint": str(record.get("license") or config.license_hint),
        "language": str(record.get("language") or config.language or detect_language(normalized)),
        "text": raw_text,
        "normalized_text": normalized,
        "raw_text_hash": stable_hash(raw_text),
        "normalized_text_hash": normalized_hash,
        "provenance_hash": provenance_hash,
        "collected_at": collected_at,
        "collector": "public_corpus_shard_builder",
        "collector_version": COLLECTOR_VERSION,
        "is_private": False,
        "is_generated": False,
        "is_eval_row": False,
        "is_mock": False,
        "quality_flags": [],
        "line_number": int(record.get("line_number") or index),
        "record_index": int(record.get("record_index") or index),
        "shard_id": shard_id,
        "target_store": "verified_store_v0_candidate",
        "learning_mode": "semantic_graph",
    }


def build_public_corpus_shard(config: PublicCorpusBuilderConfig) -> PublicCorpusShardBuildResult:
    """Build approved candidate-learning JSONL rows from a local public corpus file."""

    input_path = Path(config.input_file)
    started = time.perf_counter()
    if not input_path.exists() or not input_path.is_file():
        return PublicCorpusShardBuildResult(
            state="source_file_missing",
            mode="dry_run" if config.dry_run or not config.execute else "execute",
            rows_read=0,
            rows_accepted=0,
            rows_rejected=1,
            duplicate_rows=0,
            rejection_reasons={"source_file_missing": 1},
        )
    if not _license_allowed(config.license_hint):
        return PublicCorpusShardBuildResult(
            state="no_approved_rows",
            mode="dry_run" if config.dry_run or not config.execute else "execute",
            rows_read=0,
            rows_accepted=0,
            rows_rejected=1,
            duplicate_rows=0,
            rejection_reasons={"unknown_license": 1},
        )

    seen_hashes = _load_dedupe_hashes(config.dedupe_against_dir)
    accepted_rows: list[dict[str, Any]] = []
    rejected = 0
    duplicate_rows = 0
    reasons: dict[str, int] = {}
    collected_at = utc_now()
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    shard_id = f"{config.source_name}:{stamp}:{stable_hash(str(input_path.resolve()))[:12]}"
    rows_read = 0

    try:
        records = _iter_source_records(input_path, config.license_hint)
        for record in records:
            if config.max_seconds is not None and time.perf_counter() - started > float(config.max_seconds):
                break
            if config.max_rows is not None and len(accepted_rows) >= int(config.max_rows):
                break
            rows_read += 1
            if record.get("parse_error"):
                rejected += 1
                reason = str(record["parse_error"])
                reasons[reason] = reasons.get(reason, 0) + 1
                continue
            text = str(record.get("text") or "")
            license_hint = str(record.get("license") or config.license_hint)
            row_reasons = _quality_reasons(
                text,
                license_hint=license_hint,
                min_chars=config.min_chars,
                max_chars=config.max_chars,
            )
            normalized = clean_source_text(text)
            normalized_hash = stable_hash(normalized)
            if normalized_hash in seen_hashes:
                duplicate_rows += 1
                row_reasons.append("duplicate_normalized_text")
            if row_reasons:
                rejected += 1
                for reason in sorted(set(row_reasons)):
                    reasons[reason] = reasons.get(reason, 0) + 1
                continue
            seen_hashes.add(normalized_hash)
            accepted_rows.append(
                _approved_row(
                    config=config,
                    record=record,
                    normalized=normalized,
                    normalized_hash=normalized_hash,
                    shard_id=shard_id,
                    index=rows_read,
                    collected_at=collected_at,
                )
            )
    except UnicodeDecodeError:
        return PublicCorpusShardBuildResult(
            state="source_decode_failed",
            mode="dry_run" if config.dry_run or not config.execute else "execute",
            rows_read=rows_read,
            rows_accepted=len(accepted_rows),
            rows_rejected=rejected + 1,
            duplicate_rows=duplicate_rows,
            rejection_reasons={**reasons, "utf8_decode_error": reasons.get("utf8_decode_error", 0) + 1},
        )

    mode = "execute" if config.execute and not config.dry_run else "dry_run"
    output_path: Path | None = None
    audit_path: Path | None = None
    if mode == "execute" and accepted_rows:
        output_root = Path(config.output_dir)
        output_root.mkdir(parents=True, exist_ok=True)
        output_path = output_root / f"approved_public_corpus_{stamp}.jsonl"
        output_path.write_text(
            "\n".join(json.dumps(row, ensure_ascii=False, sort_keys=True) for row in accepted_rows) + "\n",
            encoding="utf-8",
        )
    result = PublicCorpusShardBuildResult(
        state="payloads_approved" if accepted_rows else "no_approved_rows",
        mode=mode,
        rows_read=rows_read,
        rows_accepted=len(accepted_rows),
        rows_rejected=rejected,
        duplicate_rows=duplicate_rows,
        rejection_reasons=reasons,
        output_path=str(output_path) if output_path else None,
        samples=accepted_rows[: max(0, int(config.sample_report))],
    )
    if mode == "execute":
        audit_root = Path(config.audit_dir)
        audit_root.mkdir(parents=True, exist_ok=True)
        audit_path = audit_root / f"public_corpus_shard_builder_{stamp}.json"
        audit_payload = result.to_dict() | {
            "input_file": str(input_path),
            "source_name": config.source_name,
            "license_hint": config.license_hint,
            "language": config.language,
            "output_path": str(output_path) if output_path else None,
        }
        audit_path.write_text(json.dumps(audit_payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        result = PublicCorpusShardBuildResult(**(result.to_dict() | {"audit_path": str(audit_path)}))
    return result


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build approved public corpus payload shards from local files.")
    parser.add_argument("--input-file", required=True)
    parser.add_argument("--source-name", required=True)
    parser.add_argument("--license-hint", required=True)
    parser.add_argument("--language", default="ko")
    parser.add_argument("--source-url", default="")
    parser.add_argument("--max-rows", type=int, default=None)
    parser.add_argument("--max-seconds", type=float, default=None)
    parser.add_argument("--output-dir", default=str(DEFAULT_OUTPUT_DIR))
    parser.add_argument("--dedupe-against-dir", default=None)
    parser.add_argument("--min-chars", type=int, default=24)
    parser.add_argument("--max-chars", type=int, default=1200)
    parser.add_argument("--sample-report", type=int, default=10)
    parser.add_argument("--dry-run", action="store_true", default=False)
    parser.add_argument("--execute", action="store_true", default=False)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """CLI entrypoint."""

    args = _parse_args(argv)
    config = PublicCorpusBuilderConfig(
        input_file=args.input_file,
        source_name=args.source_name,
        license_hint=args.license_hint,
        language=args.language,
        source_url=args.source_url,
        output_dir=args.output_dir,
        max_rows=args.max_rows,
        max_seconds=args.max_seconds,
        min_chars=args.min_chars,
        max_chars=args.max_chars,
        dry_run=True if not args.execute else bool(args.dry_run),
        execute=bool(args.execute),
        dedupe_against_dir=args.dedupe_against_dir,
        sample_report=args.sample_report,
    )
    result = build_public_corpus_shard(config)
    print(json.dumps(result.to_dict(), ensure_ascii=False, indent=2, sort_keys=True))
    return 0 if result.state in {"payloads_approved", "no_approved_rows", "source_file_missing"} else 2


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
